### ISSUE TITLE
Fire-PR not detecting PR View in bitbucket

### ISSUE THREAD

**Issue by dempo93** [3YOURMIND/fire-pr#8]
I installed fire pr, but when i create a PR on bb, the default "Not In Pull Request View" shows up.
Current platform

Google Chrome | 64.0.3282.140 (Official Build) (64-bit)
-- | --
Revision | a06bc1d5e8e285c70078802de990c1719ccc75e8-refs/branch-heads/3282@{#631}
OS | Linux
JavaScript | V8 6.4.388.41
Flash | 28.0.0.161 ~/.config/google-chrome/PepperFlash/28.0.0.161/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by igeligel** [comment]
This is probably because you are not in the application repo. The code for the repo is hard coded right now [here](https://github.com/3YOURMIND/fire-pr/blob/master/fire-pr-web/src/popup/App.vue#L55).

```js
const jiraIssue = branchTitle.toString().match(/B3-([0-9])*/gi)[0];
```

Basically i need to change this and see how JIRA's tags are or how to find them in the source code in a better way. Ill find a solution tonight and provide a fix i guess.

**Comment by igeligel** [comment]
Is fixed now, will deploy update to extensions tomorrow
